apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beam-mcp-server.fullname" . }}-config
  labels:
    {{- include "beam-mcp-server.labels" . | nindent 4 }}
data:
  beam_mcp_config.yaml: |
    {{- toYaml .Values.beamMcp.config | nindent 4 }} 