apiVersion: v1
kind: Service
metadata:
  name: {{ include "beam-mcp-server.fullname" . }}
  labels:
    {{- include "beam-mcp-server.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "beam-mcp-server.selectorLabels" . | nindent 4 }} 