apiVersion: v2
name: beam-mcp-server
description: A Helm chart for Apache Beam MCP Server
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - apache-beam
  - mcp
  - data-pipeline
maintainers:
  - name: Beam MCP Team
    email: beam-mcp@example.com
home: https://github.com/yourusername/beam-mcp-server
sources:
  - https://github.com/yourusername/beam-mcp-server
dependencies:
  - name: prometheus
    version: "15.10.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: "6.50.7"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled 