# Default configuration for Apache Beam MCP Server
# This is a minimal configuration to get the server running

# Server configuration
server:
  host: "127.0.0.1"
  port: 8888
  debug: true
  base_url: "http://localhost:8888"

# Service configuration
service:
  name: "beam-mcp-server"
  type: "beam"
  description: "Apache Beam MCP Server"
  version: "1.0.0"
  environment: "development"
  log_level: "INFO"

# Default runner
default_runner: direct

# Security configuration
security:
  auth_enabled: false
  auth_type: "none"

# Interface configurations
interfaces:
  jobs:
    enabled: true
  
  metrics:
    enabled: true
  
  logs:
    enabled: true
  
  savepoints:
    enabled: true
    default_savepoint_dir: /tmp/beam-savepoints

# MCP configuration
mcp:
  version: 1.0
  server_name: beam-mcp-server
  provider: apache
  log_level: INFO

# GCP configuration (not used with direct runner)
gcp:
  project_id: your-gcp-project-id
  region: us-central1

# Runner configurations
runners:
  direct:
    enabled: true
    type: "direct"
    display_name: "Direct Runner"
    description: "Local Direct Runner for testing"
    pipeline_options:
      direct_num_workers: 4
      direct_running_mode: multi_threading
      temp_location: /tmp/beam-direct-temp
      save_main_session: true
    
  dataflow:
    enabled: false
    type: "dataflow"
    display_name: "Google Cloud Dataflow"
    description: "Google Cloud Dataflow Runner"
    
  spark:
    enabled: false
    type: "spark"
    display_name: "Apache Spark"
    description: "Apache Spark Runner"
    
  flink:
    enabled: false
    type: "flink"
    display_name: "Apache Flink"
    description: "Apache Flink Runner" 