service:
  name: beam-mcp
  type: beam
  description: Apache Beam MCP Server
  version: 1.0.0

default_runner: direct

runners:
  flink:
    enabled: true
    jobmanager_url: http://localhost:8081
    flink_master: localhost:8081
    rest_url: http://localhost:8081
    jar_path: null  # Path to the Flink job jar (for non-portable pipelines)
    # Pipeline options for Flink runner
    pipeline_options:
      parallelism: 4
      checkpointing_interval: 10000  # milliseconds
      state_backend: "memory"  # "memory", "filesystem", or "rocksdb"
      tmp_dir: "/tmp/beam-flink-tmp"
      state_backend_path: "/tmp/beam-flink-state"
      savepoint_path: "/tmp/beam-flink-savepoints"
      auto_watermark_interval: 1000  # milliseconds
      streaming: false  # Set to true for streaming jobs
      
  direct:
    enabled: true
    pipeline_options:
      direct_num_workers: 4
      direct_running_mode: multi_threading
      temp_location: /tmp/beam-direct-temp
      save_main_session: true

  # Disable other runners to simplify debugging
  spark:
    enabled: false
  
  dataflow:
    enabled: false

interfaces:
  jobs:
    enabled: true
  
  metrics:
    enabled: true
  
  logs:
    enabled: true
  
  savepoints:
    enabled: true
    default_savepoint_dir: /tmp/beam-savepoints

mcp:
  version: 1.0
  server_name: beam-mcp-server
  provider: apache
  log_level: DEBUG  # Set to DEBUG to get more information

gcp:
  project_id: your-gcp-project-id  # Will be ignored since Dataflow is disabled
  region: us-central1 