service:
  name: beam-mcp
  type: beam
  description: Apache Beam MCP Server Test Configuration
  version: "1.0.0"

default_runner: direct

# MCP Settings
mcp:
  version: "1.0"
  server_name: "beam-mcp-server"
  provider: "apache"
  streaming_support: true
  log_level: "INFO"

gcp:
  project_id: servys
  region: us-central1

runners:
  dataflow:
    enabled: false
    default_project: test-project
    default_region: us-central1
  spark:
    enabled: false
    spark_master: local[*]
  flink:
    enabled: false
    jobmanager_address: localhost:8081
  direct:
    enabled: true
    options:
      direct_num_workers: 1
      direct_running_mode: in_memory
      temp_location: /tmp/beam-test
      save_main_session: true

interfaces:
  jobs:
    enabled: true
    batch_size: 100
  
  metrics:
    enabled: true
    retention_days: 1
    aggregation_interval: 10  # seconds
  
  logs:
    enabled: true
    retention_days: 1
    max_entries_per_request: 1000
  
  savepoints:
    enabled: true
    retention_days: 7
    max_concurrent_savepoints: 3

security:
  auth_enabled: false
  auth_type: none
  allowed_origins:
    - http://localhost:3000 

# API Configuration
api:
  prefix: "/api/v1"
  cors_origins: ["*"]
  base_url: "http://localhost:8088" 