global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "beam-mcp"
    scrape_interval: 15s
    static_configs:
      - targets: ["beam-mcp:8888"]
    metrics_path: /metrics

  - job_name: "flink"
    static_configs:
      - targets: ["flink-jobmanager:8081"]
    metrics_path: /metrics

  - job_name: "spark"
    static_configs:
      - targets: ["spark-master:8080"]
    metrics_path: /metrics 